Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/codespace/.local/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/codespace/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/local/python/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/codespace/.local/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/codespace/.local/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/codespace/.local/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from matplotlib import pyplot as plt
from matplotlib_venn import venn3

# Himpunan-himpunan yang diberikan
a = {1,2,5,6,7,11,12,13,14,15,18,20}
b = {2,3,4,5,6,7,8,12,13}
c = {1,2,3,6,8,9,10,13,17,18}
s = set(range(1, 21))

# Menghitung elemen-elemen diagram Venn
venn_values = (len(a - b - c), len(b - a - c), len(a & b - c), len(c - a - b), len(a & c - b), len(b & c - a), len(a & b & c))

# Membuat diagram Venn
plt.figure(figsize=(8, 6))
venn_diagram = venn3(subsets=venn_values, set_labels=('a', 'b', 'c'))

# Menampilkan diagram
plt.title("Diagram Venn untuk Himpunan a, b, dan c")
plt.show()

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[11], line 2[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mimport[39;00m pyplot [38;5;28;01mas[39;00m plt
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib_venn[39;00m [38;5;28;01mimport[39;00m venn3
[1;32m      4[0m [38;5;66;03m# Himpunan-himpunan yang diberikan[39;00m
[1;32m      5[0m a [38;5;241m=[39m {[38;5;241m1[39m,[38;5;241m2[39m,[38;5;241m5[39m,[38;5;241m6[39m,[38;5;241m7[39m,[38;5;241m11[39m,[38;5;241m12[39m,[38;5;241m13[39m,[38;5;241m14[39m,[38;5;241m15[39m,[38;5;241m18[39m,[38;5;241m20[39m}

[0;31mModuleNotFoundError[0m: No module named 'matplotlib_venn'

